### ISSUE TITLE
starting polly with an invalid driver shows success - service is not actually running

### ISSUE THREAD

**Issue by cduchesne** [emccode/polly#36]
```
$ sudo ./polly service start -f -l debug
<snip>
panic: invalid driver name

goroutine 11 [running]:
panic(0xe30440, 0xc820143a80)
        /usr/lib/go/src/runtime/panic.go:481 +0x3e6
github.com/emccode/polly/core/libstorage/server.NewWithConfig.func1(0xc82011af60)
        /home/chris/go/src/github.com/emccode/polly/core/libstorage/server/server.go:29 +0x7f
created by github.com/emccode/polly/core/libstorage/server.NewWithConfig
        /home/chris/go/src/github.com/emccode/polly/core/libstorage/server/server.go:30 +0x59
```

**Comment by cduchesne** [comment]
unable to reproduce with later version of polly starting version 0.1
